// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// LBSPR_NLLgtg
double LBSPR_NLLgtg(NumericVector starts, NumericVector LMids, NumericVector LBins, NumericVector LDat, NumericVector gtgLinfs, NumericMatrix MKMat, double MK, double Linf, int ngtg, NumericVector recP, int usePen);
RcppExport SEXP LBSPR_LBSPR_NLLgtg(SEXP startsSEXP, SEXP LMidsSEXP, SEXP LBinsSEXP, SEXP LDatSEXP, SEXP gtgLinfsSEXP, SEXP MKMatSEXP, SEXP MKSEXP, SEXP LinfSEXP, SEXP ngtgSEXP, SEXP recPSEXP, SEXP usePenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type LMids(LMidsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type LBins(LBinsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type LDat(LDatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gtgLinfs(gtgLinfsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type MKMat(MKMatSEXP);
    Rcpp::traits::input_parameter< double >::type MK(MKSEXP);
    Rcpp::traits::input_parameter< double >::type Linf(LinfSEXP);
    Rcpp::traits::input_parameter< int >::type ngtg(ngtgSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type recP(recPSEXP);
    Rcpp::traits::input_parameter< int >::type usePen(usePenSEXP);
    rcpp_result_gen = Rcpp::wrap(LBSPR_NLLgtg(starts, LMids, LBins, LDat, gtgLinfs, MKMat, MK, Linf, ngtg, recP, usePen));
    return rcpp_result_gen;
END_RCPP
}
