# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' LBSPR Optimization function for GTG model
#'
#' Internal optimization function 
#'
#' @param starts a
#' @param LMids a 
#' @param LBins a
#' @param LDat a 
#' @param gtgLinfs a
#' @param MKMat a
#' @param MK a
#' @param Linf a
#' @param ngtg a
#' @param recP a
#' @param usePen a
#' @return negative log-likelihood value 
#' @author A. Hordyk
#' @export
LBSPR_NLLgtg <- function(starts, LMids, LBins, LDat, gtgLinfs, MKMat, MK, Linf, ngtg, recP, usePen) {
    .Call('LBSPR_LBSPR_NLLgtg', PACKAGE = 'LBSPR', starts, LMids, LBins, LDat, gtgLinfs, MKMat, MK, Linf, ngtg, recP, usePen)
}

